### ISSUE TITLE
Tighten up naming conventions for `certificates` vs. `bundles`

### ISSUE THREAD

**Issue by CAGalbraith** [Future-Energy-Associates/granular_certificate_registry#75]
## Description

Currently fairly inconsistent in how certificate vs bundles are described through the code base - bundles are the objects, certificates at the individual Wh within those bundles.

## Dependencies

- with third parties, data etc.

## Tests

- [] What tests are needed to accomplish the success criteria

## Success Criteria

- [] Checkboxes describing every step needed to be taken for defining this ticket as Done.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the GranularCertificateBundle and related classes to consistently use 'bundle' terminology and clarify the relationship between bundles and certificates.

You can review changes in this commit: https://github.com/lattaai13/Future-Energy-Associates-granular_certificate_registry-75/commit/b0545265f9a38c55a04d966ce760b5e6917f2dbe.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
